import type { Metadata } from "next";
import Arial from 'next/font/local';
import { ToastContainer } from "react-toastify";
import "./globals.css";
import Header from "./modules/Header/Header";
const arial = Arial({
  src: [
    { path: "./fonts/ArialRegular.ttf", weight: "400" },
    { path: "./fonts/ArialBold.ttf", weight: "700" },
    { path: "./fonts/ArialItalic.ttf", style: "italic" },
    { path: "./fonts/ArialBoldItalic.ttf", weight: "700", style: "italic" },
    { path: "./fonts/ArialBlack.ttf", weight: "900" },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${arial.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <ToastContainer />

      </body>
    </html>
  );
}
